work on build frequency script

diff --git a/scripts/set-build-frequency b/scripts/set-build-frequency
--- a/scripts/set-build-frequency
+++ b/scripts/set-build-frequency
@@ -1,4 +1,55 @@
 #/usr/bin/env bash
 
+FREQUENCY_FILEPATH="/opt/raspberry-pi-build-server/data/build-frequency"
 
-printf $1 > /opt/raspberry-pi-build-server/data/build-frequency
+validate_arg() {
+    if [ -z $1 ]
+    then
+        echo "No parameter set"
+        exit 1
+    fi 
+    
+    case "$1" in 
+        "cron") echo "matches cron" ;;
+	"daily") echo "matches daily" ;; 
+	"weekly") echo "matches weekly" ;;
+        "monthly") echo "matches monthly";;
+        *) echo "Invalid parameter" && exit 1;;
+    esac
+}
+
+
+get_expression() {    
+
+    case "$1" in 
+        "cron") eval "$2='1 * * * * *'" ;;
+        "daily") eval "$2='2 * * * * *'" ;;
+	"weekly") eval "$2='3 * * * * *'";;
+        "monthly") eval "$2='4 * * * * *'";;
+    esac
+}
+
+
+log_frequency() {
+     printf "$1" > $FREQUENCY_FILEPATH
+}
+
+#add_frequency_to_cron() {
+
+#}
+
+#remove_frequency_from_cron() {
+
+#}
+
+
+validate_arg $1
+get_expression $1 "cron_expression"
+log_frequency "$cron_expression"
+#add_frequency_to_cron $cron_expression
+#log_frequency $cron_expression
+
+
+
+
+#printf $1 > /opt/raspberry-pi-build-server/data/build-frequency
